#!/usr/bin/env node
// CAMP-90: write public/_headers for Cloudflare Pages.
//
// Runs before every build (npm `prebuild`), so the file cannot drift out
// of step with the mode the build was made in.
//
// 🔴 Why this exists next to next.config.mjs rather than instead of it:
// Cloudflare Pages serves the built files itself and never runs Next's
// header logic, so a `headers()` block alone would mean the production
// deploy has no X-Robots-Tag at all — the exact opposite of what the
// card asks for, and invisible locally because `next start` does honour
// it. One source of truth, two emitters, and check-indexing.mjs
// verifies they agree.
//
// The file is generated, not committed: a committed _headers would say
// whatever it said the day someone last edited it.

import { mkdirSync, writeFileSync } from 'node:fs';
import { SECURITY_HEADERS } from './security-headers.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(here, '..', 'public', '_headers');

// 🔴 A build made in development mode is not a build we may ship.
//
// next.config.mjs relaxes the CSP with 'unsafe-eval' when NODE_ENV is
// development, because Next's dev compiler cannot run without it. Review
// showed that guard is keyed on the SHELL, not on the server: Next keeps
// a NODE_ENV that is already set (next/dist/bin/next: `process.env
// .NODE_ENV = process.env.NODE_ENV || defaultEnv`, with only a yellow
// warning), and `next start` serves the CSP from routes-manifest.json
// rather than re-evaluating headers(). So `NODE_ENV=development next
// build` bakes the relaxation into the production artefact, and nothing
// downstream would ever say so.
//
// This script already runs in the build's own environment, as `prebuild`
// — which makes it the one place that can turn that assumption into an
// assertion. CI never sets NODE_ENV, so this is a guard against the
// accident, not against CI.
//
// Scoped to the build: `predev` runs this same script to keep the dev
// server's generated files in step, and refusing there would only stop
// people working.
const forABuild = process.env.npm_lifecycle_event !== 'predev';
if (forABuild && process.env.NODE_ENV === 'development') {
  console.error(
    '🔴 NODE_ENV=development during a build.\n' +
      '   next.config.mjs adds \'unsafe-eval\' to the CSP in that mode, and\n' +
      '   next start serves whatever the build baked in — so this would ship\n' +
      '   a production site with unsafe-eval allowed.\n' +
      '   Unset NODE_ENV (or set it to production) and build again.',
  );
  process.exit(1);
}

const isPublic = process.env.NEXT_PUBLIC_SITE_MODE === 'public';

const lines = [
  '# Generated by scripts/gen-headers.mjs — do not edit, do not commit.',
  `# Build mode: ${isPublic ? 'public' : 'closed'}`,
  '',
  '/*',
  ...Object.entries(SECURITY_HEADERS).map(([k, v]) => `  ${k}: ${v}`),
];

if (!isPublic) {
  // Every response, not only HTML: the sitemap, llms.txt, fonts and any
  // JSON we ever add are all indexable on their own.
  lines.push('  X-Robots-Tag: noindex, nofollow');
}

lines.push('');

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'));
console.log(
  `public/_headers written for a ${isPublic ? 'PUBLIC' : 'CLOSED'} build`,
);
