#!/usr/bin/env node
// CAMP-90: write public/_headers for Cloudflare Pages.
//
// Runs before every build (npm `prebuild`), so the file cannot drift out
// of step with the mode the build was made in.
//
// 🔴 Why this exists next to next.config.mjs rather than instead of it:
// Cloudflare Pages serves the built files itself and never runs Next's
// header logic, so a `headers()` block alone would mean the production
// deploy has no X-Robots-Tag at all — the exact opposite of what the
// card asks for, and invisible locally because `next start` does honour
// it. One source of truth, two emitters, and check-indexing.mjs
// verifies they agree.
//
// The file is generated, not committed: a committed _headers would say
// whatever it said the day someone last edited it.

import { mkdirSync, writeFileSync } from 'node:fs';
import { SECURITY_HEADERS } from './security-headers.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(here, '..', 'public', '_headers');

const isPublic = process.env.NEXT_PUBLIC_SITE_MODE === 'public';

const lines = [
  '# Generated by scripts/gen-headers.mjs — do not edit, do not commit.',
  `# Build mode: ${isPublic ? 'public' : 'closed'}`,
  '',
  '/*',
  ...Object.entries(SECURITY_HEADERS).map(([k, v]) => `  ${k}: ${v}`),
];

if (!isPublic) {
  // Every response, not only HTML: the sitemap, llms.txt, fonts and any
  // JSON we ever add are all indexable on their own.
  lines.push('  X-Robots-Tag: noindex, nofollow');
}

lines.push('');

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'));
console.log(
  `public/_headers written for a ${isPublic ? 'PUBLIC' : 'CLOSED'} build`,
);
